serverInfo:
  name: "AcesListenerBitcoin"
  description: "ACES Listener implementation for Bitcoin"
  version: "1.0.0"
  websiteUrl: "https://arkaces.com"

maxScanBlockDepth: 4

bitcoinRpc:
  url: http://localhost:18332/
  username: bitcoinrpc
  password: change_this_to_a_long_random_password

server:
  port: 9090

arkAuth:
  requireAuth: false

  # Ark Network to use for fetching and broadcasting ark auth transactions
  arkNetworkConfigPath: "ark_network_config/localnet.yml"

  # The address that fees are sent to
  serviceArkAddress: "ARNJJruY6RcuYCXcwWsu4bx9kyZtntqeAx"

  # Amount of ARK required in your stake account address
  minArkStake: "0"

  # Amount of ARK to charge payment account every 24 hours to keep
  # API key active
  arkFee: "0"

logging:
  level:
    com.arkaces.aces_listener_bitcoin.BitcoinEventListener: ERROR

#spring:
#  datasource:
#    url: "jdbc:h2:/tmp/btc-listener.db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
#    driver-class-name: "org.h2.Driver"
#  jpa:
#    hibernate:
#      ddl-auto: "update"
